include(${CMAKE_CURRENT_LIST_DIR}/Generic-GNU-AVR.cmake)

set(CMAKE_C_FLAGS_INIT ${AVR_GNU_GENERIC_FLAGS})
set(CMAKE_C_OUTPUT_EXTENSION .o)
set(CMAKE_C_FLAGS_MINSIZEDEBUG ${AVR_GNU_GENERIC_FLAGS_MINSIZEDEBUG})

